export interface BookOption {
  label: string
  book: string
  testament: string
  chapters: number
}

export const options: BookOption[] = [
  {
    label: '창세기',
    book: 'genesis',
    testament: 'oldTestament',
    chapters: 50,
  },
  {
    label: '출애굽기',
    book: 'exodus',
    testament: 'oldTestament',
    chapters: 40,
  },
  {
    label: '레위기',
    book: 'leviticus',
    testament: 'oldTestament',
    chapters: 27,
  },
  {
    label: '민수기',
    book: 'numbers',
    testament: 'oldTestament',
    chapters: 36,
  },
  {
    label: '신명기',
    book: 'deuteronomy',
    testament: 'oldTestament',
    chapters: 34,
  },
  {
    label: '여호수아',
    book: 'joshua',
    testament: 'oldTestament',
    chapters: 24,
  },
  {
    label: '사사기',
    book: 'judges',
    testament: 'oldTestament',
    chapters: 21,
  },
  {
    label: '룻기',
    book: 'ruth',
    testament: 'oldTestament',
    chapters: 4,
  },
  {
    label: '사무엘상',
    book: 'firstSamuel',
    testament: 'oldTestament',
    chapters: 31,
  },
  {
    label: '사무엘하',
    book: 'secondSamuel',
    testament: 'oldTestament',
    chapters: 24,
  },
  {
    label: '열왕기상',
    book: 'firstKings',
    testament: 'oldTestament',
    chapters: 22,
  },
  {
    label: '열왕기하',
    book: 'secondKings',
    testament: 'oldTestament',
    chapters: 25,
  },
  {
    label: '역대상',
    book: 'firstChronicles',
    testament: 'oldTestament',
    chapters: 29,
  },
  {
    label: '역대하',
    book: 'secondChronicles',
    testament: 'oldTestament',
    chapters: 36,
  },
  {
    label: '에스라',
    book: 'ezra',
    testament: 'oldTestament',
    chapters: 10,
  },
  {
    label: '느헤미야',
    book: 'nehemiah',
    testament: 'oldTestament',
    chapters: 13,
  },
  {
    label: '에스더',
    book: 'esther',
    testament: 'oldTestament',
    chapters: 10,
  },
  {
    label: '욥기',
    book: 'job',
    testament: 'oldTestament',
    chapters: 42,
  },
  {
    label: '시편',
    book: 'psalms',
    testament: 'oldTestament',
    chapters: 150,
  },
  {
    label: '잠언',
    book: 'proverbs',
    testament: 'oldTestament',
    chapters: 31,
  },
  {
    label: '전도서',
    book: 'ecclesiastes',
    testament: 'oldTestament',
    chapters: 12,
  },
  {
    label: '아가',
    book: 'songOfSolomon',
    testament: 'oldTestament',
    chapters: 8,
  },
  {
    label: '이사야',
    book: 'isaiah',
    testament: 'oldTestament',
    chapters: 66,
  },
  {
    label: '예레미야',
    book: 'jeremiah',
    testament: 'oldTestament',
    chapters: 52,
  },
  {
    label: '예레미야애가',
    book: 'lamentations',
    testament: 'oldTestament',
    chapters: 5,
  },
  {
    label: '에스겔',
    book: 'ezekiel',
    testament: 'oldTestament',
    chapters: 48,
  },
  {
    label: '다니엘',
    book: 'daniel',
    testament: 'oldTestament',
    chapters: 12,
  },
  {
    label: '호세아',
    book: 'hosea',
    testament: 'oldTestament',
    chapters: 14,
  },
  {
    label: '요엘',
    book: 'joel',
    testament: 'oldTestament',
    chapters: 3,
  },
  {
    label: '아모스',
    book: 'amos',
    testament: 'oldTestament',
    chapters: 9,
  },
  {
    label: '오바댜',
    book: 'obadiah',
    testament: 'oldTestament',
    chapters: 1,
  },
  {
    label: '요나',
    book: 'jonah',
    testament: 'oldTestament',
    chapters: 4,
  },
  {
    label: '미가',
    book: 'micah',
    testament: 'oldTestament',
    chapters: 7,
  },
  {
    label: '나훔',
    book: 'nahum',
    testament: 'oldTestament',
    chapters: 3,
  },
  {
    label: '하박국',
    book: 'habakkuk',
    testament: 'oldTestament',
    chapters: 3,
  },
  {
    label: '스바냐',
    book: 'zephaniah',
    testament: 'oldTestament',
    chapters: 3,
  },
  {
    label: '학개',
    book: 'haggai',
    testament: 'oldTestament',
    chapters: 2,
  },
  {
    label: '스가랴',
    book: 'zechariah',
    testament: 'oldTestament',
    chapters: 14,
  },
  {
    label: '말라기',
    book: 'malachi',
    testament: 'oldTestament',
    chapters: 4,
  },
  {
    label: '마태복음',
    book: 'matthew',
    testament: 'newTestament',
    chapters: 28,
  },
  {
    label: '마가복음',
    book: 'mark',
    testament: 'newTestament',
    chapters: 16,
  },
  {
    label: '누가복음',
    book: 'luke',
    testament: 'newTestament',
    chapters: 24,
  },
  {
    label: '요한복음',
    book: 'john',
    testament: 'newTestament',
    chapters: 21,
  },
  {
    label: '사도행전',
    book: 'acts',
    testament: 'newTestament',
    chapters: 28,
  },
  {
    label: '로마서',
    book: 'romans',
    testament: 'newTestament',
    chapters: 16,
  },
  {
    label: '고린도전서',
    book: 'firstCorinthians',
    testament: 'newTestament',
    chapters: 16,
  },
  {
    label: '고린도후서',
    book: 'secondCorinthians',
    testament: 'newTestament',
    chapters: 13,
  },
  {
    label: '갈라디아서',
    book: 'galatians',
    testament: 'newTestament',
    chapters: 6,
  },
  {
    label: '에베소서',
    book: 'ephesians',
    testament: 'newTestament',
    chapters: 6,
  },
  {
    label: '빌립보서',
    book: 'philippians',
    testament: 'newTestament',
    chapters: 4,
  },
  {
    label: '골로새서',
    book: 'colossians',
    testament: 'newTestament',
    chapters: 4,
  },
  {
    label: '데살로니가전서',
    book: 'firstThessalonians',
    testament: 'newTestament',
    chapters: 5,
  },
  {
    label: '데살로니가후서',
    book: 'secondThessalonians',
    testament: 'newTestament',
    chapters: 3,
  },
  {
    label: '디모데전서',
    book: 'firstTimothy',
    testament: 'newTestament',
    chapters: 6,
  },
  {
    label: '디모데후서',
    book: 'secondTimothy',
    testament: 'newTestament',
    chapters: 4,
  },
  {
    label: '디도서',
    book: 'titus',
    testament: 'newTestament',
    chapters: 3,
  },
  {
    label: '빌레몬서',
    book: 'philemon',
    testament: 'newTestament',
    chapters: 1,
  },
  {
    label: '히브리서',
    book: 'hebrews',
    testament: 'newTestament',
    chapters: 13,
  },
  {
    label: '야고보서',
    book: 'james',
    testament: 'newTestament',
    chapters: 5,
  },
  {
    label: '베드로전서',
    book: 'firstPeter',
    testament: 'newTestament',
    chapters: 5,
  },
  {
    label: '베드로후서',
    book: 'secondPeter',
    testament: 'newTestament',
    chapters: 3,
  },
  {
    label: '요한일서',
    book: 'firstJohn',
    testament: 'newTestament',
    chapters: 5,
  },
  {
    label: '요한이서',
    book: 'secondJohn',
    testament: 'newTestament',
    chapters: 1,
  },
  {
    label: '요한삼서',
    book: 'thirdJohn',
    testament: 'newTestament',
    chapters: 1,
  },
  {
    label: '유다서',
    book: 'jude',
    testament: 'newTestament',
    chapters: 1,
  },
  {
    label: '요한계시록',
    book: 'revelation',
    testament: 'newTestament',
    chapters: 22,
  },
]
